thenewboston-developers/thenewboston-js

example.js
package-lock.json
package.json
rollup.config.js
src/index.ts
src/models/account.ts
src/models/index.ts
src/server-node.ts
src/utils/create-account.ts
src/utils/index.ts
src/utils/uint8array-to-hex.ts

Implements account creation with the [tweetnacl](https://www.npmjs.com/package/tweetnacl) npm package for using the box signature encryption.  I also added a type for the `params` parameter in the `server-node.ts` file.

Implement Account Creation

---

src/server-node.ts

feat: implement `ServerNode` POST request method

---

package-lock.json
package.json

Also made it so the file minifies

Added in browserify

---

src/server-node.ts

account number: d84543947090d300910f8d1b9604c0c0a56fafca6cfbe52511c1e31757188bca

feat: implement generics for axios requests and `ServerNode` methods

---

src/bank.ts
src/models/index.ts
src/models/responses/bank/config.ts
src/models/responses/bank/index.ts
src/models/responses/constants.ts
src/models/responses/index.ts

Resolves #17 
Account number: d84543947090d300910f8d1b9604c0c0a56fafca6cfbe52511c1e31757188bca

feat: type `getConfig` `Bank` method response

---

src/bank.ts

closes #14 
Account number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1

update account method for banks

---

src/account.ts
src/utils/hex-to-uint8array.ts
src/utils/index.ts
tests/account.test.js

This also fixes some of the tests so that they actually check the data.

chore: refactor account class creation

---

src/bank.ts

closes #29 
I'm not sure if I put the code in the right place, since I couldn't find any TODO comment like last time. Let me know if I need to change that.

Implement POST Upgrade Request for `ConfirmationValidator`

---

src/confirmation-validator.ts

Implement POST Primary Validator Updated for `ConfirmationValidator`

---

docs.md

closes #22 
account number: d84543947090d300910f8d1b9604c0c0a56fafca6cfbe52511c1e31757188bca

docs: add `Account` section

---

src/models/responses/primary-validator/config.ts
src/models/responses/primary-validator/index.ts

acct# 57c10f3554872103c9b91e481347c2522dd5a13757831a51b12180c09e2e50ce

[Task] Type PrimaryValidator.getConfig Method Response #36

---

src/bank.ts

We could write tests for this? #37

Implemented post blocks method

---

docs.md

[WIP] docs: Add Banks section

---

docs.md

I think this PR will have the issues resolved

[Task] Create Validator Documentation #25

---

docs.md

I did a spell check and fixed some grammatical mistakes.

Updated some documentation

---

src/index.ts
src/payment-handler.ts
src/utils/index.ts
src/utils/throw-error.ts

A code example that would work with the `PaymentHandler` would be like the following:
```js
const { PaymentHandler, Account } = require("./");
(async () => {
const handler = new PaymentHandler({
bankUrl: "http://143.110.137.54",
});
await handler.init();
const sender = new Account("SENDER_SIGNING_KEY");
await handler.sendCoins(sender, "RECIPIENT_ACCOUNT_NUMBER", 3); // the recipient can also be an instance of `Account`
})();
```
Account #: d84543947090d300910f8d1b9604c0c0a56fafca6cfbe52511c1e31757188bca

Implement Payment Handler

---

docs.md
package-lock.json

docs: PrimaryValidator Section

---

.github/workflows/lint.yml
.github/workflows/npm-publish.yml

ci: publish package

---

src/models/transaction.ts
src/payment-handler.ts

Add fee field #61

---

src/account-payment-handler.ts
src/payment-handler.ts
src/utils/index.ts
src/utils/transfer-details.ts

Send database synchronisable idempotent payment #57

---

tests/paymentHandler.test.js

test: PaymentHandler Tests

---

.eslintrc.json
package-lock.json
package.json
src/confirmation-validator.ts
src/payment-handler.ts
src/server-node.ts

Fixes #68 
Note that the github action runs the new linter and it passed.
P.S. woops just realised i branched out directly from the team's repo instead of my own forked, will take note next time.
Account Number: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[#68] Add support for eslint

---

docs/account-payment-handler.md

added Account payment handler docs

---

.gitignore
docs/account-payment-handler.md
package-lock.json
src/account-payment-handler.ts
src/payment-handler.ts
src/server-node.ts
tests/paymentHandler.test.js

Resolves: #83
I don't know if this is the best implementation. 
I used the **Transaction[]** type instead of the **TransferDetails** class for the 
methods `createTransaction()` and `sendBulkTransactions()`
Also Should i make the internal methods private

feat: Bulk payments

---

docs/bank.md
docs/index.md
src/bank.ts

feat: Get bank pv

---

docs/bank.md
docs/index.md
docs/primary-validator.md
src/bank.ts
src/primary-validator.ts

feat: Tx fees

---

docs/account.md
docs/bank.md
docs/confirmation-validator.md
src/account.ts
src/bank.ts
src/confirmation-validator.ts
src/models/crawl-data.ts
src/models/index.ts
src/models/responses/constants.ts
src/models/responses/generic/crawl.ts
src/models/signed-message.ts
src/server-node.ts
tests/account.test.js

feat: added getCrawlStatus

---

docs/bank.md
docs/confirmation-validator.md
src/bank.ts
src/confirmation-validator.ts
src/models/clean-data.ts
src/models/index.ts
src/models/responses/generic/clean.ts
src/models/responses/generic/index.ts
src/payment-handler.ts
src/server-node.ts

Feat: getCleanStatus(), startClean() and stopClean()

---

tests/bank.test.js
tests/data/bank/clean.js
tests/data/bank/index.js

tests: add clean behaviour tests

---

docs/bank.md
src/bank.ts
src/validator.ts
tests/bank.test.js

Feat: added updateBankTrust, updateValidatorTrust to bank and validator Class

---

docs/bank.md
src/bank.ts
src/validator.ts

feat: Get Methods for Single nodes

---

README.md
docs/CONTRIBUTING.md

docs: added contribution doc

---

README.md

docs: added stats to README

---

src/models/responses/confirmation-validator/config.ts
src/models/responses/primary-validator/config.ts

Resolves: #134 
@zinoadidi Need this to be updated on the npm package

Update to CV and PV Response Types

---

docs/account-payment-handler.md
docs/primary-validator.md
src/account-payment-handler.ts
src/models/transaction.ts
src/payment-handler.ts
src/utils/transfer-details.ts
tests/bank.test.js
tests/data/bank/bank_transactions.js
tests/paymentHandler.test.js

feat: Added support for memo

---

src/payment-handler.ts

---
about: trimming memo
title: save trimmed memo
---
Issue posted on discord by #Carter
> Hi, sorry I don't have enough time to create an issue and PR, but the String#trim method used at https://github.com/thenewboston-developers/thenewboston-js/blob/development/src/payment-handler.ts#L53 only returns a trimmed memo instead of mutating the original string.
Fixes # (issue)

fix: trimmed memo is added to request

---

src/models/responses/bank/config.ts
src/models/responses/confirmation-validator/config.ts
src/models/responses/constants.ts
src/models/responses/generic/clean.ts
src/models/responses/generic/crawl.ts
src/models/responses/primary-validator/config.ts
src/payment-handler.ts

---
about: 'replace types with Enum'
title: 'feat: Replaced type with enum for types with multiple values'
---
Switch all the types with multiple values to enum's so they are compatible with the account manager repo
Resolves: #158

feat: Replaced type with enum for types with multiple values

---

docs/account.md
src/account-payment-handler.ts
src/account.ts
src/payment-handler.ts
tests/account.test.js

---
about: ''
title: 'feat:Verify Signatures'
labels: ''
assignees: ''
---
A function to verify a signature when given a message, signature, and account number.
Fixes #163

feat: Verify Signatures

---

docs/index.md

---
about: 'docs: Add Account Payment Handler to docs'
title: 'docs: Add Account Payment Handler to docs'
labels: 'docs'
assignees: 'denistsoi'
---
Adds Account Payment Handler to docs.
Closes #167 

docs: Add Account Payment Handler to docs

---

src/payment-handler.ts

---
about: 'Fixes the bug in AccountPaymentHandler class'
title: 'fix: Sort the transactions in the array based on recipient value'
labels: ''
assignees: ''
---
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

fix:  bulkTransactions method throws error
